### ISSUE TITLE
Add Allure report

### ISSUE THREAD

**Issue by alcaneo** [nespresso/ntaf#31]
Reporting needs to be improved as details are often missing when something goes wrong.
One good candidate supported by Webdriverio is Allure.

I tried it a year ago but faced many issues while generating reports.
There is a version 2 now, that deserves a try.

**Comment by racodond** [comment]
@alcaneo: Are you talking about https://github.com/webdriverio/wdio-allure-reporter?
Because one issue that we were facing is open: https://github.com/webdriverio/wdio-allure-reporter/issues/43

**Comment by alcaneo** [comment]
There is a new version, if needed we could try to update wdio-allure-reporter with the last version of allure-commonjs and see if the problem is still there.
I remember one problem was to generate the report, as Allure has changed version I hope this would have solved the problem.

Also someone mentioned in a comment of the issue that now there should be something in place to catch those kind of "undefined" issues.

**Comment by racodond** [comment]
OK. Got it.

**Comment by racodond** [comment]
@alcaneo Actually neither wdio-allure-reporter nor allure-common-js really need to be updated. Those libs generate data. Those data are then processed to build the website while running the allure command. We just need to install the right version of allure on Jenkins (currently 2.2.0).

**Comment by racodond** [comment]
@alcaneo It works fine on my local Jenkins with test in errors. Let's install it on Nespresso Jenkins and see how it goes.
