### ISSUE TITLE
When cloning repo + npm install --> missing local configuration

### ISSUE THREAD

**Issue by alcaneo** [nespresso/ntaf#67]
**Step to reproduce**:
- A project with Ntaf setup exist in a repository
- A new developer clone the repo
- Run `npm install`
- Run `npm run test-local`

**Expected result**:
Tests run with local configuration

**Actual**:
Error as wdio.local.conf.js is missing

Note: Same for `npm run test-debug`

**Comment by racodond** [comment]
I updated the documentation to make it clearer.
